export const defaultLitografiaAiKnowledge = {
  moneda: 'COP',
  actualizado: '2026-05-22',
  fuente: 'COSTOS DE PRODUCCION LITOGRAFIA.pdf',
  parametros: {
    margen_utilidad_porcentaje: 40,
    iva_porcentaje: 19,
    regla_general_impresion_millar:
      'La impresion se cobra por millares completos, minimo 1 millar. Redondear hacia arriba: 300 se cobran como 1000, 1200 se cobran como 2000.',
    regla_plastificado_500_unidades: 'Para 500 unidades se cobra la mitad del valor de 1000 unidades.',
    regla_octavo:
      'La maquina de octavo solo se maneja hasta 3 tintas. Si el trabajo va a 4 tintas, se cotiza como policromia cuarto.',
    regla_sobrante_papel:
      'Agregar 100 tamanos extra sobre el tamano en que se va a imprimir. Ejemplo: si se imprime en cuarto, agregar 100 cuartos de sobrante; equivalen a 25 pliegos de 70x100 porque salen 4 cuartos por pliego.',
    regla_montaje_planchas:
      'Si varias piezas caben en el mismo tamano de impresion, se cobra un solo juego de planchas por montaje. Si frente y respaldo caben en la misma plancha, tambien se cobra un solo juego; ejemplo: brochure carta 4x4 montado en cuarto con ambas caras en la misma plancha cuesta 45000 en planchas.',
    regla_montaje_impresion:
      'La impresion se calcula por pasadas totales del montaje: tiros + retiros cuando aplica. Si frente y respaldo caben en el mismo montaje y el total de pasadas no supera 1000, se cobra un solo millar aunque sea tiro y retiro. Si el total de pasadas supera 1000, se redondea al siguiente millar. Ejemplo: 1200 brochures con 2 por montaje son 600 tiros + 600 retiros = 1200 pasadas, se cobran como 2 millares.',
  },
  costos: {
    planchas: [
      { nombre: 'Plancha metalica monocolor octavo', tintas: '1 a 3 tintas', tamano: 'octavo', valor: 10000, unidad: 'unidad' },
      { nombre: 'Plancha metalica monocolor cuarto', tintas: '1 a 3 tintas', tamano: 'cuarto', tamano_cm: '35x50', valor: 15000, unidad: 'unidad' },
      { nombre: 'Plancha metalica monocolor medio', tintas: '1 a 3 tintas', tamano: 'medio', valor: 35000, unidad: 'unidad' },
      { nombre: 'Plancha metalica monocolor pliego', tintas: '1 a 3 tintas', tamano: 'pliego', valor: 65000, unidad: 'unidad' },
      {
        nombre: 'Plancha metalica policromia octavo',
        tintas: '4 colores',
        tamano: 'octavo',
        valor: null,
        unidad: 'unidad',
        nota: 'No aplica; la maquina de octavo solo maneja hasta 3 tintas. Para 4 tintas se cotiza como policromia cuarto.',
      },
      {
        nombre: 'Plancha metalica policromia cuarto',
        tintas: '4 colores',
        tamano: 'cuarto',
        tamano_cm: '35x50',
        valor: 45000,
        unidad: 'unidad',
        regla_cobro: 'Un juego 4x0 cuesta 45000. Un trabajo 4x4 cuesta 90000 porque usa dos juegos, uno por cada cara.',
      },
      { nombre: 'Plancha metalica policromia medio', tintas: '4 colores', tamano: 'medio', valor: 95000, unidad: 'unidad' },
      { nombre: 'Plancha metalica policromia pliego', tintas: '4 colores', tamano: 'pliego', valor: 250000, unidad: 'unidad' },
    ],
    impresion: [
      { nombre: 'Impresion monocolor octavo', tintas: '1 a 3 tintas', tamano: 'octavo', valor: 15000, unidad: 'millar' },
      { nombre: 'Impresion monocolor cuarto', tintas: '1 a 3 tintas', tamano: 'cuarto', tamano_cm: '35x50', valor: 25000, unidad: 'millar' },
      { nombre: 'Impresion monocolor medio', tintas: '1 a 3 tintas', tamano: 'medio', valor: 35000, unidad: 'millar' },
      { nombre: 'Impresion pliego CMYK', tintas: 'CMYK', tamano: 'pliego', valor: 280000, unidad: 'millar' },
      { nombre: 'Impresion pliego especial', tintas: 'especial', tamano: 'pliego', valor: 385000, unidad: 'millar' },
      {
        nombre: 'Impresion policromia octavo',
        tintas: '4 colores',
        tamano: 'octavo',
        valor: null,
        unidad: 'millar',
        nota: 'No aplica; la maquina de octavo solo maneja hasta 3 tintas. Para 4 tintas se cotiza como policromia cuarto.',
      },
      {
        nombre: 'Impresion policromia cuarto',
        tintas: '4 colores',
        tamano: 'cuarto',
        tamano_cm: '35x50',
        valor: 60000,
        unidad: 'millar',
        regla_cobro: 'Se cobra por millares completos, minimo 1 millar.',
      },
      { nombre: 'Impresion policromia medio', tintas: '4 colores', tamano: 'medio', valor: 110000, unidad: 'millar' },
      { nombre: 'Impresion policromia pliego', tintas: '4 colores', tamano: 'pliego', valor: 520000, unidad: 'millar' },
    ],
    papeles: [
      { nombre: 'Bond 75 gms', valor: 503, unidad: 'pliego 70x100' },
      { nombre: 'Bond 90 gms', valor: 545, unidad: 'pliego 70x100' },
      { nombre: 'Bond 115 gms', valor: 668, unidad: 'pliego 70x100' },
      { nombre: 'Bond 75 gms', valor: 426, unidad: 'pliego 90x60' },
      { nombre: 'Bond 90 gms', valor: 448, unidad: 'pliego 90x60' },
      { nombre: 'Bond 115 gms', valor: null, unidad: 'pliego 90x60', nota: 'No aplica.' },
      { nombre: 'Eart Pack 70 gms', valor: 451, unidad: 'pliego 70x100' },
      { nombre: 'Eart Pack 90 gms', valor: 552, unidad: 'pliego 70x100' },
      { nombre: 'Eart Pack 226 gms', valor: 1290, unidad: 'pliego 70x100' },
      { nombre: 'Eart Pack 70 gms', valor: 371, unidad: 'pliego 90x60' },
      { nombre: 'Eart Pack 90 gms', valor: 448, unidad: 'pliego 90x60' },
      { nombre: 'Eart Pack 226 gms', valor: null, unidad: 'pliego 90x60', nota: 'No aplica.' },
      { nombre: 'Propalcote 115 gms', valor: 648, unidad: 'pliego 70x100' },
      { nombre: 'Propalcote 150 gms', valor: 828, unidad: 'pliego 70x100' },
      { nombre: 'Propalcote 240 gms', valor: 1291, unidad: 'pliego 70x100' },
      { nombre: 'Propalcote 300 gms', valor: 1650, unidad: 'pliego 70x100' },
      { nombre: 'Propalcote 115 gms', valor: 579, unidad: 'pliego 90x60' },
      { nombre: 'Propalcote 150 gms', valor: 665, unidad: 'pliego 90x60' },
      { nombre: 'Propalcote 240 gms', valor: 980, unidad: 'pliego 90x60' },
      { nombre: 'Propalcote 300 gms', valor: 1305, unidad: 'pliego 90x60' },
      { nombre: 'Adhesivo P3H', valor: 2200, unidad: 'pliego 70x100' },
      { nombre: 'Adhesivo P4', valor: 2700, unidad: 'pliego 70x100' },
      { nombre: 'Papel quimico original 1 copia', valor: 985, unidad: 'pliego 70x100' },
      { nombre: 'Papel quimico original 2 copias', valor: 1600, unidad: 'pliego 70x100' },
    ],
    corte_por_pliego: [
      { nombre: 'Media carta', medidas_cm: '22x14', cantidad_por_pliego: 22 },
      { nombre: 'Media oficio', medidas_cm: '22x16.5', cantidad_por_pliego: 18 },
      { nombre: 'Media octavo', medidas_cm: '25x17.5', cantidad_por_pliego: 16 },
      { nombre: 'Carta', medidas_cm: '22x28', cantidad_por_pliego: 10 },
      { nombre: 'Oficio', medidas_cm: '22x33', cantidad_por_pliego: 9 },
      { nombre: 'Legal', medidas_cm: '22x35', cantidad_por_pliego: 8 },
      { nombre: 'Octavo', medidas_cm: '25x35', cantidad_por_pliego: 8 },
      { nombre: 'Doble carta', medidas_cm: '28x43', cantidad_por_pliego: 5 },
      { nombre: 'Cuarto 60x90', medidas_cm: '30x45', cantidad_por_pliego: 4 },
      { nombre: 'Cuarto', medidas_cm: '35x50', cantidad_por_pliego: 4 },
      { nombre: 'Medio 60x90', medidas_cm: '60x45', cantidad_por_pliego: 2 },
      { nombre: 'Medio', medidas_cm: '70x50', cantidad_por_pliego: 2 },
      { nombre: 'Pliego 60x90', medidas_cm: '60x90', cantidad_por_pliego: 1 },
      { nombre: 'Pliego', medidas_cm: '70x100', cantidad_por_pliego: 1 },
    ],
    plastificado: [
      { nombre: 'Plastificado carta', medidas_cm: '22x28', valor: 80000, unidad: '1000 unidades' },
      { nombre: 'Plastificado oficio', medidas_cm: '22x33', valor: 85000, unidad: '1000 unidades' },
      { nombre: 'Plastificado octavo', medidas_cm: '25x35', valor: 95000, unidad: '1000 unidades' },
      { nombre: 'Plastificado doble carta', medidas_cm: '28x43', valor: 150000, unidad: '1000 unidades' },
      { nombre: 'Plastificado cuarto', medidas_cm: '35x50', valor: 140000, unidad: '1000 unidades' },
      { nombre: 'Plastificado medio', medidas_cm: '70x50', valor: 280000, unidad: '1000 unidades' },
      { nombre: 'Plastificado pliego', medidas_cm: '70x100', valor: 560000, unidad: '1000 unidades' },
    ],
    terminados: [
      { nombre: 'Holmet', rango: '100 unidades', valor: 1000, unidad: 'unidad' },
      { nombre: 'Holmet', rango: '500 unidades', valor: 800, unidad: 'unidad' },
      { nombre: 'Holmet', rango: '1000 unidades', valor: 700, unidad: 'unidad' },
      { nombre: 'Compaginado', rango: '1 - 500', valor: 10, unidad: 'hoja' },
      { nombre: 'Compaginado', rango: '501 - 1000', valor: 8, unidad: 'hoja' },
      { nombre: 'Compaginado', rango: '1000 en adelante', valor: 7, unidad: 'hoja' },
      { nombre: 'Pegue iman', rango: 'cupo', valor: 40000, unidad: 'servicio' },
      { nombre: 'Pegue iman', rango: 'doble cupo', valor: 60000, unidad: 'servicio' },
      { nombre: 'Pegue iman', rango: 'triple cupo', valor: 80000, unidad: 'servicio' },
      { nombre: 'Armado de carpetas', rango: 'silicona 1000 unidades', valor: 80000, unidad: 'servicio' },
      { nombre: 'Armado de carpetas', rango: 'silicona 500 unidades', valor: 50000, unidad: 'servicio' },
      { nombre: 'Armado de carpetas', rango: 'silicona minima', valor: 40000, unidad: 'servicio' },
      {
        nombre: 'Juego tapadura carta',
        rango: 'hasta 100',
        valor: 5000,
        unidad: 'unidad',
        nota: 'Incluye carton y guardas; no incluye impresion de caratulas.',
      },
      {
        nombre: 'Juego tapadura carta',
        rango: '101 en adelante',
        valor: 4500,
        unidad: 'unidad',
        nota: 'Incluye carton y guardas; no incluye impresion de caratulas.',
      },
      {
        nombre: 'Juego tapadura media carta',
        rango: 'hasta 100',
        valor: 4000,
        unidad: 'unidad',
        nota: 'Incluye carton y guardas; no incluye impresion de caratulas.',
      },
      {
        nombre: 'Juego tapadura media carta',
        rango: '101 en adelante',
        valor: 3500,
        unidad: 'unidad',
        nota: 'Incluye carton y guardas; no incluye impresion de caratulas.',
      },
      { nombre: 'Armado libretas', rango: '1 libreta', valor: 5000, unidad: 'unidad', nota: 'Incluye compaginado y acabado lincon.' },
      { nombre: 'Armado libretas', rango: '2 libretas', valor: 6000, unidad: 'unidad', nota: 'Incluye compaginado y acabado lincon.' },
      { nombre: 'Armado libretas', rango: '5 libretas', valor: 2400, unidad: 'unidad', nota: 'Incluye compaginado y acabado lincon.' },
      { nombre: 'Armado libretas', rango: '10 libretas en adelante', valor: 1800, unidad: 'unidad', nota: 'Incluye compaginado y acabado lincon.' },
      { nombre: 'Anillado media carta', rango: 'mas de 100', valor: 2500, unidad: 'unidad', nota: 'Solo servicio de anillado.' },
      { nombre: 'Anillado adhesivo P4', rango: 'mas de 100', valor: 3500, unidad: 'unidad', nota: 'Solo servicio de anillado.' },
      { nombre: 'Cosida', rango: 'cosido', valor: 80000, unidad: 'servicio' },
      { nombre: 'Cosida', rango: 'al hilo', valor: 500, unidad: 'unidad' },
      { nombre: 'Refile cartilla', valor: 200, unidad: 'cartilla', fuente: 'Costo previo indicado por usuario' },
      { nombre: 'Grafa de caratula', valor: 35000, unidad: 'millar', fuente: 'Costo previo indicado por usuario' },
      { nombre: 'Refile y plegado', valor: 20000, unidad: 'millar', fuente: 'Costo previo indicado por usuario' },
    ],
  },
  notas: [
    'Los costos del PDF redefinen valores anteriores: propalcote 150 gms queda en 828 por pliego 70x100. El usuario corrigio plancha policromia cuarto a 45000, plancha policromia medio a 95000, impresion policromia cuarto a 60000 por millar, plastificado cuarto a 140000, medio a 280000 y pliego a 560000 por 1000 unidades.',
    'El PDF escribe EART PACK; se conserva ese nombre en la base para coincidir con la lista.',
    'Papeles diferentes se cotizan aparte segun la nota del PDF.',
    'Se conservaron refile cartilla, grafa de caratula y refile y plegado porque ya habian sido definidos por el usuario y no aparecen redefinidos en el PDF.',
  ],
} as const