CREATE TYPE "ProductKind" AS ENUM ('FINISHED_GOOD', 'RAW_MATERIAL', 'SUPPLY', 'SERVICE', 'COMPOSITE');

CREATE TYPE "ProductSupplyMethod" AS ENUM ('PURCHASE', 'MANUFACTURE', 'MAKE_TO_ORDER', 'MIXED', 'INTERNAL_SERVICE');

ALTER TABLE "materiales"
ADD COLUMN "autoCreateWorkOrder" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "productKind" "ProductKind" NOT NULL DEFAULT 'FINISHED_GOOD',
ADD COLUMN "supplyMethod" "ProductSupplyMethod" NOT NULL DEFAULT 'PURCHASE',
ADD COLUMN "tracksInventory" BOOLEAN NOT NULL DEFAULT true;
