'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useI18n } from '@/components/providers/i18n-provider'
import { ErpPageHero } from '@/components/dashboard/erp-page-chrome'
import { NominaSurfaceCallout } from '@/components/dashboard/nomina-surface-callout'
import { NominaSubnav } from '@/components/dashboard/nomina-subnav'
import { DataViewToggle } from '@/components/dashboard/data-view-toggle'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { useDataViewMode } from '@/hooks/use-data-view-mode'
import { nominaHref } from '@/lib/nomina-routes'
import type { PayrollEmployeeDocumentRow, PayrollEmployeeRow, PayrollPayslipRow, PayrollPeriodRow } from '@/lib/payroll'
import { formatCurrency } from '@/lib/utils'

const EMPTY_FORM = {
  employeeId: '',
  periodId: '',
  title: '',
  category: 'PAGO',
  documentType: 'DESPRENDIBLE',
  status: 'BORRADOR',
  signatureRequired: 'true',
  signatureStatus: 'PENDIENTE',
  visibleInPortal: 'true',
  deliveryChannel: 'PORTAL',
  fileFormat: 'PDF',
  requestedAt: '',
  deliveredAt: '',
  signedAt: '',
  expiresAt: '',
  notes: '',
}

function formatDate(value: string | null | undefined, locale: string) {
  if (!value) return '—'
  try {
    return new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(new Date(value))
  } catch {
    return value
  }
}

export default function NominaReportesPage() {
  const [periods, setPeriods] = useState<PayrollPeriodRow[]>([])
  const [payslips, setPayslips] = useState<PayrollPayslipRow[]>([])
  const [documents, setDocuments] = useState<PayrollEmployeeDocumentRow[]>([])
  const [employees, setEmployees] = useState<PayrollEmployeeRow[]>([])
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [form, setForm] = useState(EMPTY_FORM)
  const { mode, setMode } = useDataViewMode('nomina.reportes', 'list')
  const { language } = useI18n()
  const locale = language === 'en' ? 'en-US' : 'es-CO'

  const copy = language === 'en'
    ? {
        eyebrow: 'Documents admin',
        title: 'E-signature and Documents',
        description: 'Administrative payroll document tray for delivery, portal visibility and electronic signature before the collaborator consumes or signs each asset.',
        stats: {
          pending: 'Pending signature',
          signed: 'Signed',
          payslips: 'Payslips',
          pendingHint: 'Needs employee action',
          signedHint: 'Closed digitally',
          payslipsHint: 'Available payment history',
        },
        actions: { create: 'Create document', save: 'Save changes', add: 'Create document', cancel: 'Cancel', edit: 'Edit', remove: 'Delete' },
        tabs: { docs: 'Documents', payslips: 'Payslips' },
        docs: {
          title: 'Labor document tray',
          description: 'Store contract addendums, payroll receipts and internal policies with signature workflow.',
        },
        payslips: {
          title: 'Recent payslip history',
          description: 'Real payslip history generated by employee and payroll period.',
        },
        dialog: {
          create: 'Create labor document',
          edit: 'Edit labor document',
          description: 'Manage delivery channel, portal visibility and electronic signature status from payroll.',
        },
        labels: {
          employee: 'Employee',
          period: 'Period',
          noPeriod: 'No period',
          title: 'Title',
          category: 'Category',
          documentType: 'Document type',
          status: 'Status',
          signatureRequired: 'Requires signature',
          signatureStatus: 'Signature status',
          visibleInPortal: 'Visible in portal',
          deliveryChannel: 'Delivery channel',
          fileFormat: 'File format',
          requestedAt: 'Requested at',
          deliveredAt: 'Delivered at',
          signedAt: 'Signed at',
          expiresAt: 'Expires at',
          notes: 'Notes',
          netPay: 'Net pay',
        },
        yes: 'Yes',
        no: 'No',
        signed: 'Signed',
        pending: 'Pending',
      }
    : {
        eyebrow: 'Documentos RRHH',
        title: 'Firma Electrónica y Gestión de Documentos',
        description: 'Bandeja administrativa para documentos laborales, entregas, visibilidad en portal y trazabilidad de firma antes de que el colaborador consuma o firme cada activo.',
        stats: {
          pending: 'Pendientes de firma',
          signed: 'Firmados',
          payslips: 'Desprendibles',
          pendingHint: 'Requieren acción del colaborador',
          signedHint: 'Cerrados digitalmente',
          payslipsHint: 'Historial de pago disponible',
        },
        actions: { create: 'Crear documento', save: 'Guardar cambios', add: 'Crear documento', cancel: 'Cancelar', edit: 'Editar', remove: 'Eliminar' },
        tabs: { docs: 'Documentos', payslips: 'Desprendibles' },
        docs: {
          title: 'Bandeja documental laboral',
          description: 'Guarda otrosíes, desprendibles y políticas internas con flujo de firma y entrega.',
        },
        payslips: {
          title: 'Historial reciente de desprendibles',
          description: 'Histórico real de desprendibles generados por período y empleado.',
        },
        dialog: {
          create: 'Crear documento laboral',
          edit: 'Editar documento laboral',
          description: 'Administra canal de entrega, visibilidad en portal y estado de firma electrónica desde nómina.',
        },
        labels: {
          employee: 'Empleado',
          period: 'Período',
          noPeriod: 'Sin período',
          title: 'Título',
          category: 'Categoría',
          documentType: 'Tipo documento',
          status: 'Estado',
          signatureRequired: 'Requiere firma',
          signatureStatus: 'Estado de firma',
          visibleInPortal: 'Visible en portal',
          deliveryChannel: 'Canal de entrega',
          fileFormat: 'Formato',
          requestedAt: 'Solicitado',
          deliveredAt: 'Entregado',
          signedAt: 'Firmado',
          expiresAt: 'Vence',
          notes: 'Notas',
          netPay: 'Neto',
        },
        yes: 'Sí',
        no: 'No',
        signed: 'Firmado',
        pending: 'Pendiente',
      }

  async function load() {
    const [periodsRes, payslipsRes, documentsRes, employeesRes] = await Promise.all([
      fetch('/api/nomina/periodos', { cache: 'no-store' }),
      fetch('/api/nomina/desprendibles', { cache: 'no-store' }),
      fetch('/api/nomina/documentos', { cache: 'no-store' }),
      fetch('/api/nomina/empleados', { cache: 'no-store' }),
    ])
    const [periodsJson, payslipsJson, documentsJson, employeesJson] = await Promise.all([
      periodsRes.json().catch(() => null),
      payslipsRes.json().catch(() => null),
      documentsRes.json().catch(() => null),
      employeesRes.json().catch(() => null),
    ])

    const nextPeriods = (periodsJson?.data as PayrollPeriodRow[] | undefined) ?? []
    const nextEmployees = (employeesJson?.data as PayrollEmployeeRow[] | undefined) ?? []
    setPeriods(nextPeriods)
    setPayslips((payslipsJson?.data as PayrollPayslipRow[] | undefined) ?? [])
    setDocuments((documentsJson?.data as PayrollEmployeeDocumentRow[] | undefined) ?? [])
    setEmployees(nextEmployees)
    setForm((current) => ({
      ...current,
      employeeId: current.employeeId || nextEmployees[0]?.id || '',
      periodId: current.periodId || nextPeriods[0]?.id || '',
    }))
  }

  useEffect(() => {
    let cancelled = false
    async function initialLoad() {
      if (cancelled) return
      await load()
    }
    void initialLoad()
    return () => {
      cancelled = true
    }
  }, [])

  function openCreate() {
    setEditingId(null)
    setError(null)
    setForm({
      ...EMPTY_FORM,
      employeeId: employees[0]?.id || '',
      periodId: periods[0]?.id || '',
      requestedAt: new Date().toISOString().slice(0, 10),
    })
    setDialogOpen(true)
  }

  function openEdit(item: PayrollEmployeeDocumentRow) {
    setEditingId(item.id)
    setError(null)
    setForm({
      employeeId: item.employeeId,
      periodId: item.periodId ?? '',
      title: item.title,
      category: item.category,
      documentType: item.documentType,
      status: item.status,
      signatureRequired: String(item.signatureRequired),
      signatureStatus: item.signatureStatus,
      visibleInPortal: String(item.visibleInPortal),
      deliveryChannel: item.deliveryChannel,
      fileFormat: item.fileFormat,
      requestedAt: item.requestedAt?.slice(0, 10) ?? '',
      deliveredAt: item.deliveredAt?.slice(0, 10) ?? '',
      signedAt: item.signedAt?.slice(0, 10) ?? '',
      expiresAt: item.expiresAt?.slice(0, 10) ?? '',
      notes: item.notes ?? '',
    })
    setDialogOpen(true)
  }

  async function handleSave() {
    setSaving(true)
    setError(null)
    const payload = {
      ...(editingId ? { id: editingId } : {}),
      ...form,
      periodId: form.periodId || null,
      signatureRequired: form.signatureRequired === 'true',
      visibleInPortal: form.visibleInPortal === 'true',
    }
    const res = await fetch('/api/nomina/documentos', {
      method: editingId ? 'PUT' : 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
    const json = (await res.json().catch(() => null)) as { ok?: boolean; error?: string } | null
    if (!res.ok || !json?.ok) {
      setError(json?.error ?? (language === 'en' ? 'Could not save labor document' : 'No fue posible guardar el documento laboral'))
      setSaving(false)
      return
    }
    setDialogOpen(false)
    setEditingId(null)
    setForm(EMPTY_FORM)
    await load()
    setSaving(false)
  }

  async function handleDelete(id: string) {
    if (!window.confirm(language === 'en' ? 'Delete this document?' : '¿Eliminar este documento?')) return
    const res = await fetch('/api/nomina/documentos', {
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id }),
    })
    const json = (await res.json().catch(() => null)) as { ok?: boolean; error?: string } | null
    if (!res.ok || !json?.ok) {
      setError(json?.error ?? (language === 'en' ? 'Could not delete document' : 'No fue posible eliminar el documento'))
      return
    }
    await load()
  }

  const pendingSignature = documents.filter((item) => item.signatureRequired && item.signatureStatus !== 'FIRMADA')
  const signedDocuments = documents.filter((item) => item.signatureStatus === 'FIRMADA')

  return (
    <div className="space-y-4">
      <ErpPageHero
        eyebrow={copy.eyebrow}
        title={copy.title}
        description={copy.description}
        actions={
          <>
            <Button asChild className="rounded-2xl">
              <Link href={nominaHref('periodos')}>{language === 'en' ? 'Open payroll periods' : 'Abrir períodos'}</Link>
            </Button>
            <Button asChild variant="outline" className="rounded-2xl bg-white/90">
              <Link href={nominaHref('portal-empleado')}>{language === 'en' ? 'View collaborator portal' : 'Ver portal del colaborador'}</Link>
            </Button>
          </>
        }
        stats={[
          { label: copy.stats.pending, value: pendingSignature.length, hint: copy.stats.pendingHint, tone: 'amber' },
          { label: copy.stats.signed, value: signedDocuments.length, hint: copy.stats.signedHint, tone: 'teal' },
          { label: copy.stats.payslips, value: payslips.length, hint: copy.stats.payslipsHint, tone: 'sky' },
        ]}
      />

      <NominaSubnav />

      <NominaSurfaceCallout
        adminTitle={language === 'en' ? 'Document delivery and signature workflow are managed here.' : 'Aquí se administra la entrega documental y el flujo de firma.'}
        adminDescription={language === 'en' ? 'RRHH publishes, tracks and closes labor documents before or while they are exposed to the collaborator.' : 'RRHH publica, rastrea y cierra documentos laborales antes o durante su exposición al colaborador.'}
        employeeTitle={language === 'en' ? 'The collaborator only receives visible assets and pending signatures.' : 'El colaborador solo recibe activos visibles y firmas pendientes.'}
        employeeDescription={language === 'en' ? 'Portal visibility and signature status here define what appears in self-service.' : 'La visibilidad en portal y el estado de firma aquí definen lo que aparece en autoservicio.'}
        primaryHref={nominaHref('portal-empleado')}
        primaryLabel={language === 'en' ? 'Open collaborator portal' : 'Abrir portal del colaborador'}
        secondaryHref={nominaHref('periodos')}
        secondaryLabel={language === 'en' ? 'Go to payroll cycles' : 'Ir a ciclos de nómina'}
      />

      <div className="flex justify-end gap-2">
        <DataViewToggle mode={mode} onChange={setMode} />
        <Button className="rounded-xl" onClick={openCreate}>{copy.actions.create}</Button>
      </div>

      <Tabs defaultValue="documents" className="space-y-4">
        <TabsList className="grid w-full max-w-md grid-cols-2 rounded-2xl">
          <TabsTrigger value="documents">{copy.tabs.docs}</TabsTrigger>
          <TabsTrigger value="payslips">{copy.tabs.payslips}</TabsTrigger>
        </TabsList>

        <TabsContent value="documents">
          <Card className="rounded-[26px] border-slate-200">
            <CardHeader>
              <CardTitle>{copy.docs.title}</CardTitle>
              <CardDescription>{copy.docs.description}</CardDescription>
            </CardHeader>
            <CardContent className={mode === 'grid' ? 'grid gap-3 md:grid-cols-2' : 'space-y-3'}>
              {documents.map((item) => (
                <div key={item.id} className={mode === 'grid' ? 'rounded-[22px] border border-slate-200 bg-white p-4' : 'rounded-[18px] border border-slate-200 bg-white px-4 py-3'}>
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <div className="font-semibold text-slate-950">{item.title}</div>
                      <div className="text-sm text-slate-500">{item.employeeName} · {item.periodLabel}</div>
                    </div>
                    <span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-slate-700">{item.documentType}</span>
                  </div>
                  <div className="mt-3 grid gap-2 text-sm text-slate-600 md:grid-cols-2">
                    <div>{copy.labels.category}: {item.category}</div>
                    <div>{copy.labels.status}: {item.status}</div>
                    <div>{copy.labels.signatureStatus}: {item.signatureStatus}</div>
                    <div>{copy.labels.deliveryChannel}: {item.deliveryChannel}</div>
                    <div>{copy.labels.visibleInPortal}: {item.visibleInPortal ? copy.yes : copy.no}</div>
                    <div>{copy.labels.fileFormat}: {item.fileFormat}</div>
                    <div>{copy.labels.requestedAt}: {formatDate(item.requestedAt, locale)}</div>
                    <div>{copy.labels.signedAt}: {formatDate(item.signedAt, locale)}</div>
                  </div>
                  {item.notes ? <div className="mt-2 text-sm text-slate-600">{copy.labels.notes}: {item.notes}</div> : null}
                  <div className="mt-3 flex justify-end gap-2">
                    <Button variant="outline" className="rounded-xl" onClick={() => openEdit(item)}>{copy.actions.edit}</Button>
                    <Button variant="outline" className="rounded-xl" onClick={() => void handleDelete(item.id)}>{copy.actions.remove}</Button>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="payslips">
          <Card className="rounded-[26px] border-slate-200">
            <CardHeader>
              <CardTitle>{copy.payslips.title}</CardTitle>
              <CardDescription>{copy.payslips.description}</CardDescription>
            </CardHeader>
            <CardContent className={mode === 'grid' ? 'grid gap-3 md:grid-cols-2' : 'space-y-3'}>
              {payslips.map((receipt) => (
                <div key={receipt.id} className={mode === 'grid' ? 'flex flex-col gap-3 rounded-[22px] border border-slate-200 bg-white p-4' : 'flex flex-col gap-2 rounded-[18px] border border-slate-200 bg-white px-4 py-3 md:flex-row md:items-center md:justify-between'}>
                  <div>
                    <div className="font-semibold text-slate-950">{receipt.employeeName}</div>
                    <div className="text-sm text-slate-500">{receipt.periodLabel} · {formatDate(receipt.paymentDate, locale)}</div>
                  </div>
                  <div className="flex items-center gap-3 text-sm text-slate-600">
                    <span>{copy.labels.netPay}: {formatCurrency(receipt.netPay)}</span>
                    <span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-slate-700">{receipt.deliveredBy}</span>
                    <span className={receipt.signed ? 'rounded-full bg-emerald-100 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-emerald-800' : 'rounded-full bg-amber-100 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-amber-800'}>
                      {receipt.signed ? copy.signed : copy.pending}
                    </span>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-2xl rounded-[28px]">
          <DialogHeader>
            <DialogTitle>{editingId ? copy.dialog.edit : copy.dialog.create}</DialogTitle>
            <DialogDescription>{copy.dialog.description}</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="grid gap-2 md:col-span-2"><Label>{copy.labels.employee}</Label><Select value={form.employeeId} onValueChange={(value) => setForm((current) => ({ ...current, employeeId: value }))}><SelectTrigger><SelectValue placeholder={copy.labels.employee} /></SelectTrigger><SelectContent>{employees.map((employee) => <SelectItem key={employee.id} value={employee.id}>{employee.fullName}</SelectItem>)}</SelectContent></Select></div>
            <div className="grid gap-2 md:col-span-2"><Label>{copy.labels.period}</Label><Select value={form.periodId || '__none__'} onValueChange={(value) => setForm((current) => ({ ...current, periodId: value === '__none__' ? '' : value }))}><SelectTrigger><SelectValue placeholder={copy.labels.noPeriod} /></SelectTrigger><SelectContent><SelectItem value="__none__">{copy.labels.noPeriod}</SelectItem>{periods.map((period) => <SelectItem key={period.id} value={period.id}>{period.label}</SelectItem>)}</SelectContent></Select></div>
            <div className="grid gap-2 md:col-span-2"><Label>{copy.labels.title}</Label><Input value={form.title} onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} /></div>
            <div className="grid gap-2"><Label>{copy.labels.category}</Label><Select value={form.category} onValueChange={(value) => setForm((current) => ({ ...current, category: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="PAGO">Pago</SelectItem><SelectItem value="CONTRATO">Contrato</SelectItem><SelectItem value="POLITICA">Política</SelectItem><SelectItem value="CERTIFICADO">Certificado</SelectItem></SelectContent></Select></div>
            <div className="grid gap-2"><Label>{copy.labels.documentType}</Label><Select value={form.documentType} onValueChange={(value) => setForm((current) => ({ ...current, documentType: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="DESPRENDIBLE">Desprendible</SelectItem><SelectItem value="OTROSI">Otrosí</SelectItem><SelectItem value="POLITICA">Política</SelectItem><SelectItem value="CERTIFICADO">Certificado</SelectItem></SelectContent></Select></div>
            <div className="grid gap-2"><Label>{copy.labels.status}</Label><Select value={form.status} onValueChange={(value) => setForm((current) => ({ ...current, status: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="BORRADOR">Borrador</SelectItem><SelectItem value="ENVIADO">Enviado</SelectItem><SelectItem value="ENTREGADO">Entregado</SelectItem><SelectItem value="ARCHIVADO">Archivado</SelectItem></SelectContent></Select></div>
            <div className="grid gap-2"><Label>{copy.labels.signatureStatus}</Label><Select value={form.signatureStatus} onValueChange={(value) => setForm((current) => ({ ...current, signatureStatus: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="PENDIENTE">Pendiente</SelectItem><SelectItem value="ENVIADA">Enviada</SelectItem><SelectItem value="FIRMADA">Firmada</SelectItem><SelectItem value="NO_REQUIERE">No requiere</SelectItem></SelectContent></Select></div>
            <div className="grid gap-2"><Label>{copy.labels.signatureRequired}</Label><Select value={form.signatureRequired} onValueChange={(value) => setForm((current) => ({ ...current, signatureRequired: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="true">{copy.yes}</SelectItem><SelectItem value="false">{copy.no}</SelectItem></SelectContent></Select></div>
            <div className="grid gap-2"><Label>{copy.labels.visibleInPortal}</Label><Select value={form.visibleInPortal} onValueChange={(value) => setForm((current) => ({ ...current, visibleInPortal: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="true">{copy.yes}</SelectItem><SelectItem value="false">{copy.no}</SelectItem></SelectContent></Select></div>
            <div className="grid gap-2"><Label>{copy.labels.deliveryChannel}</Label><Select value={form.deliveryChannel} onValueChange={(value) => setForm((current) => ({ ...current, deliveryChannel: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="PORTAL">Portal</SelectItem><SelectItem value="EMAIL">Email</SelectItem><SelectItem value="PDF">PDF</SelectItem><SelectItem value="FISICO">Físico</SelectItem></SelectContent></Select></div>
            <div className="grid gap-2"><Label>{copy.labels.fileFormat}</Label><Select value={form.fileFormat} onValueChange={(value) => setForm((current) => ({ ...current, fileFormat: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="PDF">PDF</SelectItem><SelectItem value="DOCX">DOCX</SelectItem><SelectItem value="XLSX">XLSX</SelectItem></SelectContent></Select></div>
            <div className="grid gap-2"><Label>{copy.labels.requestedAt}</Label><Input type="date" value={form.requestedAt} onChange={(event) => setForm((current) => ({ ...current, requestedAt: event.target.value }))} /></div>
            <div className="grid gap-2"><Label>{copy.labels.deliveredAt}</Label><Input type="date" value={form.deliveredAt} onChange={(event) => setForm((current) => ({ ...current, deliveredAt: event.target.value }))} /></div>
            <div className="grid gap-2"><Label>{copy.labels.signedAt}</Label><Input type="date" value={form.signedAt} onChange={(event) => setForm((current) => ({ ...current, signedAt: event.target.value }))} /></div>
            <div className="grid gap-2"><Label>{copy.labels.expiresAt}</Label><Input type="date" value={form.expiresAt} onChange={(event) => setForm((current) => ({ ...current, expiresAt: event.target.value }))} /></div>
            <div className="grid gap-2 md:col-span-2"><Label>{copy.labels.notes}</Label><Textarea value={form.notes} onChange={(event) => setForm((current) => ({ ...current, notes: event.target.value }))} rows={3} /></div>
          </div>
          {error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div> : null}
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>{copy.actions.cancel}</Button>
            <Button onClick={() => void handleSave()} disabled={saving}>{saving ? (language === 'en' ? 'Saving...' : 'Guardando...') : editingId ? copy.actions.save : copy.actions.add}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}