ALTER TABLE "litografia_print_profiles"
ADD COLUMN "anchoUtilCm" DOUBLE PRECISION NOT NULL DEFAULT 70,
ADD COLUMN "altoUtilCm" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN "separacionPiezasCm" DOUBLE PRECISION NOT NULL DEFAULT 0;
