-- AlterEnum
ALTER TYPE "PosPaymentMethod" ADD VALUE IF NOT EXISTS 'CREDIT';
ALTER TYPE "PosPaymentMethod" ADD VALUE IF NOT EXISTS 'DEBIT_CARD';
ALTER TYPE "PosPaymentMethod" ADD VALUE IF NOT EXISTS 'CREDIT_CARD';
ALTER TYPE "PosPaymentMethod" ADD VALUE IF NOT EXISTS 'CHECK';
ALTER TYPE "PosPaymentMethod" ADD VALUE IF NOT EXISTS 'BONUS';
ALTER TYPE "PosPaymentMethod" ADD VALUE IF NOT EXISTS 'LETTER';
ALTER TYPE "PosPaymentMethod" ADD VALUE IF NOT EXISTS 'VALE';

-- AlterTable
ALTER TABLE "pos_invoices" ADD COLUMN IF NOT EXISTS "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "pos_invoices" ADD COLUMN IF NOT EXISTS "otherTaxesAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
